### ISSUE TITLE
[improvement] skip "SPECTRAL_PROFILE_DATA" for single channel images

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/old-carta-backend#68]
If the image has only one channel, the generation of "SPECTRAL_PROFILE_DATA" should be skipped. This could prevent some crash events if the image header does not contain sufficient frequency/velocity information.

**Comment by duidae** [comment]
fixed in commit aa40e8c83b79b8a8caa204ad5541a100e0a6e8bd
